ms:
  app:
    id: e2076d1e-f717-4c1e-966f-a3f303074a25
    scopes: User.Read,Files.Read.All
    authority: https://login.microsoftonline.com/common/

logging:
  level:
    me.avo.yunyin: TRACE

spring:
  datasource:
    url: jdbc:h2:file:./db;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
  main:
    lazy-initialization: true